apiVersion: apps/v1
kind: Deployment
metadata:
  name: oms-mail
  namespace: app
  labels:
    app: oms-mail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oms-mail
  template:
    metadata:
      labels:
        app: oms-mail
    spec:
      containers:
      - name: oms-mail
        image: manishsrivastavaggn/oms-mail:changeMePlease
        ports:
        - containerPort: 8080
   